services:
  - type: web
    name: blind-chefs-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn blind_chefs_backend.wsgi
    staticPublishPath: staticfiles
    envVars:
      - key: DEBUG
        value: 'False'
