# Generated by Django 5.2 on 2025-04-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_condiment_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condiment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
